### ISSUE TITLE
size is not included in the list

### ISSUE THREAD

**Issue by liudonghua123** [xresloader/upload-to-github-release#5]
A few minutes ago, my github action all failed with the following errors. Last night, it was ok.

<details>

```bash
Create release 1.0.0+1 for Thiswind-Learning/python_exercise_builder success
Start uploading asset: python_exercise_builder-macos-1.0.0+1.zip(size: 56763762) ...
Upload asset: python_exercise_builder-macos-1.0.0+1.zip failed => Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /Users/runner/runners/2.169.1/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13220:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Start uploading asset(1 retry): python_exercise_builder-macos-1.0.0+1.zip(size: 56763762) ...
============================= v4 API: query { repository (owner:"Thiswind-Learning", name:"python_exercise_builder") } =============================
Upload asset(1 retry): python_exercise_builder-macos-1.0.0+1.zip failed => Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /Users/runner/runners/2.169.1/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13220:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Start uploading asset(2 retry): python_exercise_builder-macos-1.0.0+1.zip(size: 56763762) ...
============================= v4 API: query { repository (owner:"Thiswind-Learning", name:"python_exercise_builder") } =============================
Upload asset(2 retry): python_exercise_builder-macos-1.0.0+1.zip failed => Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /Users/runner/runners/2.169.1/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13220:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Start uploading asset(3 retry): python_exercise_builder-macos-1.0.0+1.zip(size: 56763762) ...
============================= v4 API: query { repository (owner:"Thiswind-Learning", name:"python_exercise_builder") } =============================
Upload asset(3 retry): python_exercise_builder-macos-1.0.0+1.zip failed => Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /Users/runner/runners/2.169.1/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13220:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Upload asset: python_exercise_builder-macos-1.0.0+1.zip failed => Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
HttpError: Validation Failed: {"resource":"ReleaseAsset","code":"custom","field":"size","message":"size is not included in the list"}
    at /Users/runner/runners/2.169.1/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:13220:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
</details>

**Comment by owt5008137** [comment]
@liudonghua123 It should be OK now.

**Comment by liudonghua123** [comment]
@owt5008137 Thanks, it works now. 😄
